export interface Country {
    altSpellings: string [],
    area?: number,
    borders: string [],
    callingCode: string[],
    capital: string,
    cca2: string,
    cca3: string,
    ccn3: string,
    currency: string[],
    demonym: string,
    gini?: number,
    language: string[],
    languageCodes: string[],
    latlng: number[],
    name: string,
    nativeName: string,
    population: number,
    region: string,
    relevance: string,
    subregion: string,
    timezones?: string[],
    tld: string[],
    translations: any
}